version: ~> 1.0
language: c
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main'
      key_url: 'https://packages.confluent.io/rpm/5.3/archive.key'	
    packages:
    - libjansson-dev
    - libmicrohttpd-dev
    - librdkafka-dev
script:
  - make test
